version: '3'
networks:
  app-tier:
services:
  server:
    build: 
      context: ./server
    ports:
      - "3000:8080"
    command: fresh
    volumes:    
      - ./server:/go/src/server
    


    