version: '3'
networks:
  app-tier:
    driver: bridge
services:
  server:
    build: 
      context: ./server
    ports:
      - "3000:8080"
    command: fresh
    volumes:    
      - ./server:/go/src/server
    networks:
      - app-tier
    links: 
      - mongodb
  mongodb:
    build: ./db
    volumes:
      - ./db/mongodb:/var/lib/mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
    networks:
      - app-tier


    